%% make all of the figures for ppt
clear toPlot SDOSessionData
load('D:\Storage\SchoolWork\BU\ME734_Spring2021\Project\ME734_FluidDynamics\single_Tjoin_1.mat')

dataset = SDOSessionData.Data.Workspace.LocalWorkspace;

%% make the array of data figures to plot
toPlot(1) = struct(...
    'x_axis_index',1,...
    'x_axis_label','length_A',...
    'y_axis_index',2,...
    'y_axis_label','length_B',...
    'Req_index',3,...
    'Req_label','FG(A o B)',...
    'dataset','couse_length_results',...
    'save_name','LTL_lengths_simple_model'...
    );

toPlot(2) = struct(...
    'x_axis_index',1,...
    'x_axis_label','height_A',...
    'y_axis_index',2,...
    'y_axis_label','height_B',...
    'Req_index',3,...
    'Req_label','FG(A o B)',...
    'dataset','heights_results',...
    'save_name','LTL_heights_simple_model'...
    );

toPlot(3) = struct(...
    'x_axis_index',1,...
    'x_axis_label','height_A',...
    'y_axis_index',2,...
    'y_axis_label','width_A',...
    'Req_index',3,...
    'Req_label','FG(A o B)',...
    'dataset','pipeA_results',...
    'save_name','LTL_pipeA_simple_model'...
    );

plot_struct(toPlot,dataset)
%% second set
clear toPlot SDOSessionData
load('D:\Storage\SchoolWork\BU\ME734_Spring2021\Project\ME734_FluidDynamics\Realistic_Model_sasession.mat');
dataset = SDOSessionData.Data.Workspace.LocalWorkspace;

toPlot(1) = struct(...
    'x_axis_index',1,...
    'x_axis_label','height_A',...
    'y_axis_index',2,...
    'y_axis_label','height_B',...
    'Req_index',3,...
    'Req_label','FG(A o B) \wedge FG(D o E) \wedge FG(C o F)',...
    'dataset','AB_height_results',...
    'save_name','LTL_AB_heights_realModel'...
    );

toPlot(2) = struct(...
    'x_axis_index',1,...
    'x_axis_label','height_A',...
    'y_axis_index',2,...
    'y_axis_label','height_C',...
    'Req_index',3,...
    'Req_label','FG(A o B) \wedge FG(D o E) \wedge FG(C o F)',...
    'dataset','AC_height_results',...
    'save_name','LTL_AC_heights_realModel'...
    );

toPlot(3) = struct(...
    'x_axis_index',1,...
    'x_axis_label','height_C',...
    'y_axis_index',2,...
    'y_axis_label','height_E',...
    'Req_index',3,...
    'Req_label','FG(A o B) \wedge FG(D o E) \wedge FG(C o F)',...
    'dataset','CE_height_results',...
    'save_name','LTL_CE_heights_realModel'...
    );

toPlot(4) = struct(...
    'x_axis_index',1,...
    'x_axis_label','Q_A',...
    'y_axis_index',2,...
    'y_axis_label','Q_B',...
    'Req_index',5,...
    'Req_label','FG(A o B) \wedge FG(D o E) \wedge FG(C o F)',...
    'dataset','flowrate_results',...
    'save_name','LTL_AB_flowrates_realModel'...
    );

toPlot(5) = struct(...
    'x_axis_index',1,...
    'x_axis_label','Q_A',...
    'y_axis_index',3,...
    'y_axis_label','Q_D',...
    'Req_index',5,...
    'Req_label','FG(A o B) \wedge FG(D o E) \wedge FG(C o F)',...
    'dataset','flowrate_results',...
    'save_name','LTL_AB_flowrates_realModel'...
    );

toPlot(6) = struct(...
    'x_axis_index',1,...
    'x_axis_label','height_A',...
    'y_axis_index',2,...
    'y_axis_label','width_A',...
    'Req_index',3,...
    'Req_label','FG(A o B) \wedge FG(D o E) \wedge FG(C o F)',...
    'dataset','pipe_A_results',...
    'save_name','LTL_pipe_A_realModel'...
    );

plot_struct(toPlot,dataset)

%% 
clear toPlot SDOSessionData
load('D:\Storage\SchoolWork\BU\ME734_Spring2021\Project\ME734_FluidDynamics\Trap_Model_sasession_take2.mat');
dataset = SDOSessionData.Data.Workspace.LocalWorkspace;

toPlot(1) = struct(...
    'x_axis_index',1,...
    'x_axis_label','L_{bypass}',...
    'y_axis_index',2,...
    'y_axis_label','R_{trap}',...
    'Req_index',3,...
    'Req_label','FG(not excape)',...
    'dataset','EvalResult',...
    'save_name','droplet_Leaving_Trap'...
    );
plot_struct(toPlot,dataset)
%% make figures of simulink diagrams
initRealModel
figure
snapshotModel('Realistic_Model');

initMonteCarlo
figure
snapshotModel('Single_junction_MonteCarlo');
figure
snapshotModel('Single_junction_MonteCarlo/LTL_transitionSystem/Chart');
figure
snapshotModel('SinglePipe_UT');

%% utility functions
function [] = plot_struct(toPlot,dataset)
for itr = toPlot
%% load data
    data = table2array(dataset.(itr.dataset).getAllData);
    grid_size(1) = size(unique(data(:,1)),1);
    grid_size(2) = size(unique(data(:,2)),1);
%% make figure
    fid = figure('Name',itr.save_name,...% name it
        'PaperSize',[12,12],...
        'Units','in',...% make it big
        'position',[0,0,12,12],...% make it big
        'PaperUnits','in',...% change print units
        'PaperPosition',[0,0,12,12]...% print size
    );% hid the figure
%% select data to plot
    [X,Y] = meshgrid(unique(data(:,itr.x_axis_index)),unique(data(:,itr.y_axis_index)));
    F = scatteredInterpolant(data(:,itr.x_axis_index),...
                  data(:,itr.y_axis_index),...
                  data(:,itr.Req_index));
    Z = F(X,Y);
    contourf(X,Y,Z)
    xlabel(itr.x_axis_label,'Interpreter','tex','FontSize',20)
    ylabel(itr.y_axis_label,'Interpreter','tex','FontSize',20)
    title(itr.Req_label,'Interpreter','tex','FontSize',20)
    grid on
%% clean up the figure to print to pdf
    fid.PaperPositionMode = 'auto';
    fig_pos = fid.PaperPosition;
    fid.PaperSize = [fig_pos(3) fig_pos(4)];
    hA = fid.Children;
    outerpos = hA.OuterPosition;
    ti = [0.100,0.100,0.050,0.050];
    left = outerpos(1) + ti(1);
    bottom = outerpos(2) + ti(2);
    ax_width = outerpos(3) - ti(1) - ti(3);
    ax_height = outerpos(4) - ti(2) - ti(4);
    hA.Position = [left bottom ax_width ax_height];
    %% print figure to know name and close the figure after
    print(fid,[itr.save_name],'-dpdf')
    print(fid,[itr.save_name],'-dpng')
end
end